### ISSUE TITLE
fisherman/get missing?

### ISSUE THREAD

**Issue by efaden** [igalic/anicode#16]
I get the following error after installing wither fisher.

fetching https://codeload.github.com/anicode/tar.gz/master
fisher: cannot add github.com/anicode -- is this a valid package?

**Comment by Markcial** [comment]
we had some organisation changes recently, the packages now use a different naming.

In order to install this fish package you have to use the path of the package using the maintainer.

That means that if you want to install anicode you have to run this command: 

    fisher add igalic/anicode

**Comment by igalic** [comment]
@Markcial but where did `fisherman/get` move?

**Comment by Markcial** [comment]
I updated the fishfile, it is on the fishpkg organisation => fishpkg/fish-get

**Comment by igalic** [comment]
since that now has also been (re)moved, i've dropped the dependency
